repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0  # Use the latest version
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/psf/black
    rev: 24.2.0  # Use the latest version
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/hhatto/autopep8
    rev: v2.0.4  # Use the latest version
    hooks:
      - id: autopep8
        args: ["--in-place", "--aggressive"]
  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0  # Use the latest version
    hooks:
      - id: flake8
