repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0  # Use the latest version
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: local
    hooks:
      - id: clear-pycache
        name: Clear __pycache__ and .pyc files
        entry: ./clear_pycache.sh
        language: script
        always_run: true
        pass_filenames: false
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: pytest
        language: system
        types: [python]
        pass_filenames: false
  - repo: local
    hooks:
      - id: coverage-check
        name: Coverage Check
        entry: ./check_coverage.sh
        language: script
        pass_filenames: false
        always_run: true
  - repo: https://github.com/psf/black
    rev: 24.2.0  # Use the latest version
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0  # Use the latest version
    hooks:
      - id: flake8
  - repo: https://github.com/seddonym/import-linter
    rev: v2.0
    hooks:
      - id: import-linter
